---
settings:
  name: Release Notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ja-jp,us-en,zh-cn,zh-tw,ko-kr
sidebar:
  entries:
  - title: Cloud Manager リリースノート
    url: "/index.html"
  - title: 最近の変更
    url: "/whats-new.html"
  - title: リリースノートインデックス
    url: "/release-notes-index.html"
homepage:
  tiles:
  - title: 新機能
    links:
    - title: Cloud Manager での最新の変更点
      url: whats-new.html
  - title: サービス別リリースノート
    links:
    - title: リリースノートインデックス
      url: release-notes-index.html
  - title: ブログコミュニティ
    links:
    - title: ネットアップコミュニティ
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Cloud Central のブログです
      url: https://cloud.netapp.com/blog
    - title: クラウドに関する Web セミナー
      url: https://cloud.netapp.com/events
product-family:
  name: Cloud Manager
  repo: cloud-manager-family
  sidebar_label: All Cloud Manager documentation
