---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features,cloud manager, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery' 
summary: BlueXPプラットフォームの一部である クラウド サービス の最新の変更点について説明します 
---
= BlueXPの最近の変更点
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPプラットフォームの一部である クラウド サービス の最新の変更点について説明します完全なリリース履歴については、 link:release-notes-index.html["リリースノートの全セット"] 個々のサービスごと。



== 管理機能

このセクションでは、BlueXPの管理機能に関連する新機能(アカウント、コネクタ、クラウドプロバイダの資格情報など)について説明します。



=== 2025年6月9日



==== コネクタ3.9.53

BlueXP コネクタのこのリリースには、セキュリティの改善とバグ修正が含まれています。

3.9.53リリースは、標準モードと制限モードで使用できます。



==== ディスク容量使用状況アラート

通知センターに、コネクタのディスク領域の使用状況に関するアラートが含まれるようになりました。 link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#monitor-disk-space["もっと詳しく知る。"^]



==== 監査の改善

タイムラインにユーザーのログインとログアウトのイベントが表示されるようになりました。ログインアクティビティがいつ発生したかを確認できるため、監査やセキュリティ監視に役立ちます。組織管理者ロールを持つAPIユーザーは、ログインしたユーザーのメールアドレスをタイムラインに表示できます。  `includeUserData=true``パラメータは次のようになります。  `/audit/<account_id>?includeUserData=true` 。



==== BlueXPでKeystoneサブスクリプション管理が利用可能

BlueXP から NetApp Keystone サブスクリプションを管理できます。

link:https://docs.netapp.com/us-en/keystone-staas/index.html["BlueXP での Keystone サブスクリプション管理について学習します。"^]



==== BlueXP  IDおよびアクセス管理（IAM）



===== 多要素認証（MFA）

フェデレーションされていないユーザーは、BlueXPアカウントで多要素認証（MFA）を有効にしてアカウントのセキュリティを強化できるようになりました。BlueXP管理者は、ユーザーのMFA設定を管理し、必要に応じて個々のユーザーのMFAをリセットまたは無効化できます。これは標準モードでのみサポートされます。

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-user-settings.html#task-user-mfa["自分自身に多要素認証を設定する方法について説明します。"^] link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-manage-members-permissions.html#manage-mfa["ユーザーに対する多要素認証の管理について学習します。"^]



==== ワークロード

BlueXP の認証情報ページから Amazon FSx for NetApp ONTAP の認証情報を表示および削除できるようになりました。



=== 2025年5月29日



==== プライベートモードリリース（3.9.52）

新しいプライベートモードリリースをからダウンロードできるようになりました。 https://mysupport.netapp.com/site/downloads["NetAppサポートサイト"^]

3.9.52リリースでは、BlueXP  の次のコンポーネントとサービスが更新されています。

[cols="3*"]
|===
| コンポーネントまたはサービス | このリリースに含まれるバージョン | 前回のプライベートモードリリースからの変更点 


| コネクタ | 3.9.52、3.9.51 | にアクセス https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#connector-3-9-50["BlueXP  Connectorページの新機能"]し、バージョン3.9.52および3.9.50の変更点を参照してください。 


| バックアップとリカバリ | 2025年5月12日 | に行く https://docs.netapp.com/us-en/bluexp-backup-recovery/whats-new.html["BlueXP  バックアップ/リカバリページの新機能"^] 2025 年 5 月のリリースに含まれる変更を参照してください。 


| 分類 | 2025年5月12日（バージョン1.43） | にアクセス https://docs.netapp.com/us-en/bluexp-classification/whats-new.html["BlueXP  分類ページの新機能"^]し、1.38リリースから1.371.41リリースに含まれる変更点を参照してください。 
|===
アップグレード方法を含むプライベートモードの詳細については、次を参照してください。

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["プライベートモードの詳細"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["BlueXPのプライベートモードでの利用を開始する方法"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["プライベートモードの使用時にコネクタをアップグレードする方法について説明します。"]




=== 2025年5月12日



==== コネクタ3.9.52

このリリースのBlueXP  Connectorには、セキュリティのマイナーな改善とバグの修正、およびいくつかの追加アップデートが含まれています。

現時点では、3.9.52リリースは標準モードと制限モードで使用できます。



===== Docker 27およびDocker 28のサポート

コネクタでDocker 27とDocker 28がサポートされるようになりました。



===== Cloud Volumes ONTAP

Cloud Volumes ONTAPノードは、コネクタがコンプライアンス違反または14日間以上ダウンしている場合でもシャットダウンしなくなりました。CloudVolumes ONTAPは、コネクタへのアクセスを失った場合でも、イベント管理メッセージを送信します。この変更は、コネクタが長期間ダウンした場合でも、Cloud Volumes ONTAPが動作を継続できるようにするためのものです。コネクタのコンプライアンス要件は変更されません。



==== Keystoneの管理はBlueXP  で可能

BlueXP  のNetApp Keystoneベータ版では、Keystone管理機能へのアクセスが追加されました。NetApp Keystoneベータ版のサインアップページには、BlueXP  の左側のナビゲーションバーからアクセスできます。



==== BlueXP  IDおよびアクセス管理（IAM）



===== 新しいストレージ管理の役割

ストレージ管理者、システム正常性スペシャリスト、ストレージ閲覧者の役割が利用可能であり、ユーザーに割り当てることができます。

これらのロールを使用すると、組織内のどのユーザーがストレージ リソースを検出および管理できるかを管理できるほか、ストレージの正常性情報を表示したり、ソフトウェアの更新を実行したりすることもできます。

これらのロールは、次のストレージ リソースへのアクセスを制御するためにサポートされています。

* Eシリーズシステム
* StorageGRID システム
* オンプレミスの ONTAP システム


これらのロールを使用して、次の BlueXP サービスへのアクセスを制御することもできます。

* ソフトウェアの更新
* デジタルアドバイザ
* 運用の耐障害性
* 経済効率
* 持続可能性


次のロールが追加されました:

* *ストレージ管理者*
+
組織内のストレージリソースの健全性、ガバナンス、検出を管理します。このロールは、ストレージリソースのソフトウェアアップデートも実行できます。

* *システムヘルススペシャリスト*
+
組織内のストレージリソースの健全性とガバナンスを管理します。このロールは、ストレージリソースのソフトウェアアップデートも実行できます。作業環境を変更または削除することはできません。

* *ストレージビューア*
+
ストレージの健全性情報とガバナンス データを表示します。

+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["アクセスロールについて説明します。"^]





== アラート



=== 2024年10月7日



==== BlueXP  アラートリストページ

容量が少ないかパフォーマンスが低いONTAPクラスタをすばやく特定し、可用性の範囲を測定して、セキュリティリスクを特定できます。容量、パフォーマンス、保護、可用性、セキュリティ、構成に関連するアラートを表示できます。



==== アラートの詳細

アラートの詳細にドリルダウンして、推奨事項を確認できます。



==== ONTAP System Managerにリンクされたクラスタの詳細の表示

BlueXP  アラートを使用すると、ONTAPストレージ環境に関連付けられているアラートを表示し、ONTAP System Managerにリンクされている詳細にドリルダウンできます。

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["BlueXP  アラートの詳細"]です。



== ONTAP 対応の Amazon FSX



=== 2025年6月29日



==== 資格情報の更新

FSx for ONTAP ファイルシステムの認証情報と権限を設定すると、BlueXP の認証情報ページにリダイレクトされます。このページから、FSx for ONTAP の認証情報の名前を変更したり、削除したりできます。

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/requirements/task-setting-up-permissions-fsx.html["FSx for ONTAP ファイルシステムの権限を設定する"]



==== 2つのFSx for ONTAPファイルシステム間でのデータ複製のサポート

BlueXP コンソールから 2 つの FSx for ONTAP ファイル システム間でデータ レプリケーションが利用できるようになりました。

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-manage-working-environment.html#replicate-data["データのレプリケート"]



=== 2025年5月4日



==== トラッカー応答サポート

TrackerでAPI応答が返されるようになり、タスクに関連するREST API出力を確認できるようになりました。



==== AWS Secrets Managerのリンク認証のサポート

AWS Secrets Managerのシークレットを使用してリンクを認証できるようになり、BlueXP  ワークロードに保存されているクレデンシャルを使用する必要がなくなりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["LambdaリンクでFSx for ONTAPファイルシステムに接続"]



==== FSx for ONTAPファイルシステムのベストプラクティスを実装

BlueXP  ワークロードは、ファイルシステム構成の適切な設計ステータスを確認できるダッシュボードを提供します。この分析を活用して、FSx for ONTAPファイルシステムのベストプラクティスを実装できます。ファイルシステム構成の分析には、SSD容量のしきい値、スケジュールされたローカルスナップショット、FSx for ONTAPのスケジュールされたバックアップ、データ階層化、リモートデータレプリケーションなどの構成が含まれます。

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["ファイルシステム構成の適切に設計された分析をご紹介します"]
* link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_well-architected/improve-configurations.html["ファイルシステムのベストプラクティスの実装"]




==== ファイルシステムの問題に対する適切に設計された通知

BlueXP  コンソールで、適切に設計された問題があるFSx for ONTAPファイルシステムに、ファイルシステムに修正が必要な問題があることを示す通知がキャンバスに表示されるようになりました。



==== 権限に関する用語を更新

ワークロード ファクトリのユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。



=== 2025年3月30日



==== IAM：SimulatePermissionPolicy権限の更新

管理できるようになりまし `iam:SimulatePrincipalPolicy`AWSアカウントのクレデンシャルを追加したり、生成AIワークロードなどの新しいワークロード機能を追加したりするときに、BlueXP  コンソールから権限をた。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["アクセス権参照変更ログ"^]



== Amazon S3ストレージ



=== 2023年3月5日



==== BlueXPから新しいバケットを追加できるようになりました

BlueXP CanvasでAmazon S3バケットを表示できるようになりました。BlueXP  から直接、新しいバケットを追加したり、既存のバケットのプロパティを変更したりできるようになりました。 https://docs.netapp.com/us-en/bluexp-s3-storage/task-add-s3-bucket.html["新しいAmazon S3バケットを追加する方法をご覧ください"]です。



== Azure BLOBストレージ



=== 2023年6月5日



==== BlueXPから新しいストレージアカウントを追加できるようになりました

BlueXP CanvasでAzure Blob Storageを表示できるようになりました。新しいストレージアカウントを追加したり、既存のストレージアカウントのプロパティをBlueXP  から直接変更したりできるようになりました。 https://docs.netapp.com/us-en/bluexp-blob-storage/task-add-blob-storage.html["新しいAzure BLOBストレージアカウントを追加する方法をご覧ください"]です。



== Azure NetApp Files の特長



=== 2025年1月13日



==== BlueXP  でのネットワーク機能のサポート

BlueXP  からAzure NetApp Filesでボリュームを設定する際に、ネットワーク機能を指定できるようになりました。これは、ネイティブのAzure NetApp Filesで利用可能な機能と連動しています。



=== 2024年6月12日



==== 新しい権限が必要です

BlueXPからAzure NetApp Filesボリュームを管理するには、次の権限が必要です。

Microsoft.Network/virtualNetworks/subnets/read

この権限は、仮想ネットワークサブネットを読み取るために必要です。

現在BlueXPからAzure NetApp Filesを管理している場合は、以前に作成したMicrosoft Entraアプリケーションに関連付けられているカスタムロールにこの権限を追加する必要があります。

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html["Microsoft Entraアプリケーションをセットアップし、カスタムロール権限を表示する方法について説明します。"]です。



=== 2024年4月22日



==== ボリュームテンプレートのサポートの廃止

テンプレートからボリュームを作成することはできなくなりました。この操作はBlueXP修正サービスに関連付けられていましたが、このサービスは廃止されました。



== バックアップとリカバリ



=== 2025 年 6 月 9 日

このBlueXP  バックアップ/リカバリリリースには、次の更新が含まれています。



==== インデックスカタログのサポートの更新

2025年2月、データ復元の「検索と復元」メソッドで使用するインデックス作成機能のアップデート（インデックスカタログv2）を導入しました。前回のリリースでは、オンプレミス環境におけるデータインデックス作成のパフォーマンスが大幅に向上しました。今回のリリースでは、Amazon Web Services、Microsoft Azure、Google Cloud Platform（GCP）環境でインデックスカタログがご利用いただけるようになりました。

新規のお客様の場合、すべての新規環境では Indexed Catalog v2 がデフォルトで有効になっています。既存のお客様の場合は、環境のインデックスを再作成することで Indexed Catalog v2 を活用できます。

.インデックス作成を有効にするにはどうすればよいですか。
データのリストアにSearch & Restore方式を使用する前に、ボリュームまたはファイルのリストア元となる各ソース作業環境で[Indexing]を有効にする必要があります。検索と復元を実行するときは、「*インデックスを有効にする*」オプションを選択します。

インデックスカタログはすべてのボリュームとバックアップ ファイルを追跡できるため、検索が迅速かつ効率的になります。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["検索と復元を使用してONTAPデータを復元する方法"]。



==== Azure プライベート リンク エンドポイントとサービス エンドポイント

BlueXP バックアップ＆リカバリは通常、クラウドプロバイダーとプライベートエンドポイントを確立し、様々な保護タスクを処理します。今回のリリースでは、BlueXP バックアップ＆リカバリによるプライベートエンドポイントの自動作成を有効または無効にできるオプション設定が導入されました。これは、プライベートエンドポイントの作成プロセスをより細かく制御したい場合に役立ちます。

保護を有効にするとき、または復元プロセスを開始するときに、このオプションを有効または無効にすることができます。

この設定を無効にすると、BlueXP のバックアップとリカバリが正常に機能するために、プライベートエンドポイントを手動で作成する必要があります。適切な接続がないと、バックアップとリカバリのタスクを正常に実行できない可能性があります。



==== ONTAP S3 での SnapMirror からクラウドへの再同期のサポート

前回のリリースでは、SnapMirror to Cloud Resync（SM-C Resync）のサポートが導入されました。この機能は、NetApp環境におけるボリューム移行時のデータ保護を効率化します。今回のリリースでは、ONTAP S3に加え、WasabiやMinIOなどの他のS3互換プロバイダーでもSM-C Resyncのサポートが追加されました。



==== StorageGRID 用の独自のバケットを用意する

作業環境のオブジェクトストレージにバックアップファイルを作成すると、BlueXP バックアップ＆リカバリはデフォルトで、ユーザーが設定したオブジェクトストレージアカウント内にバックアップファイル用のコンテナ（バケットまたはストレージアカウント）を作成します。以前は、この設定をオーバーライドして、Amazon S3、Azure Blob Storage、Google Cloud Storage 用の独自のコンテナを指定できました。今回のリリースでは、独自の StorageGRID オブジェクトストレージコンテナを使用できるようになりました。

を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["独自のオブジェクトストレージコンテナを作成する"]



=== 2025年5月13日

このBlueXP  バックアップ/リカバリリリースには、次の更新が含まれています。



==== ボリューム移行のためのSnapMirrorからクラウドへの再同期

SnapMirrorからクラウドへの再同期機能は、NetApp環境でのボリューム移行時のデータ保護と継続性を合理化します。SnapMirror論理レプリケーション（LRSE）を使用して、オンプレミスのNetApp環境から別の環境、またはCloud Volumes ONTAPやCloud Volumes Serviceなどのクラウドベースのソリューションにボリュームを移行する場合、SnapMirrorからクラウドへの再同期により、既存のクラウドバックアップに影響を与えずに運用できます。

この機能により、時間とリソースを大量に消費するベースライン再処理が不要になり、移行後もバックアップ処理を継続できます。この機能は、FlexVolとFlexGroupの両方をサポートするワークロードマイグレーションシナリオで役立ちます。ONTAPバージョン9.16.1以降で使用できます。

SnapMirrorからクラウドへの再同期は、環境全体でバックアップの継続性を維持することで運用効率を高め、ハイブリッドクラウドやマルチクラウドのデータ管理の複雑さを軽減します。

再同期処理の実行方法の詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-migrate-volumes-snapmirror-cloud-resync.html["SnapMirrorを使用したボリュームのクラウドへの再同期"]。



==== サードパーティ製MinIOオブジェクトストアのサポート（プレビュー）

BlueXP  のバックアップとリカバリでは、MinIOを中心にサードパーティのオブジェクトストアもサポートされるようになりました。この新しいプレビュー機能を使用すると、バックアップとリカバリのニーズに合わせてS3互換オブジェクトストアを活用できます。

このプレビュー版では、すべての機能がリリースされる前に、サードパーティのオブジェクトストアとの強固な統合を確保したいと考えています。この新しい機能について検討し、サービスの強化に役立つフィードバックを提供することをお勧めします。


IMPORTANT: この機能は本番環境では使用しないでください。

*プレビューモードの制限*

この機能はプレビュー中ですが、次のような制限があります。

* Bring Your Own Bucket（BYOB）はサポートされていません。
* ポリシーでDataLockを有効にすることはできません。
* ポリシーでアーカイブモードを有効にすることはできません。
* オンプレミスのONTAP環境のみがサポートされます。
* MetroClusterはサポートされていません。
* バケットレベルの暗号化を有効にするオプションはサポートされていません。


* はじめに *

このプレビュー機能を使用するには、BlueXP  コネクタでフラグを有効にする必要があります。その後、バックアップセクションで*サードパーティ互換*オブジェクトストアを選択して、MinIOのサードパーティオブジェクトストアの接続の詳細を保護ワークフローに入力できます。

プレビュー機能を有効にする方法については、を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-preview-enable.html["BlueXP  バックアップ/リカバリのプレビュー機能を有効にする"]。



=== 2025年4月16日

このBlueXP  バックアップ/リカバリリリースには、次の更新が含まれています。



==== UIの改善

このリリースでは、インターフェイスが簡素化され、操作性が向上しています。

* [Volumes]テーブルから[Aggregate]列を削除し、[V2]ダッシュボードの[Volume]テーブルから[Snapshot Policy]列、[Backup Policy]列、および[Replication Policy]列を削除すると、レイアウトがより効率的になります。
* アクティブ化されていない作業環境をドロップダウンリストから除外すると、インターフェイスがすっきりし、ナビゲーションが効率的になり、読み込みが高速になります。
* [タグ]列でのソートが無効になっていても、タグを表示できるため、重要な情報に簡単にアクセスできます。
* 保護アイコンのラベルを削除すると、見た目がきれいになり、ロード時間が短縮されます。
* 作業環境のアクティブ化プロセスでは、検出プロセスが完了するまでダイアログボックスにロードアイコンが表示されてフィードバックが提供されるため、システムの運用の透明性と信頼性が向上します。




==== ボリュームダッシュボードの強化（プレビュー）

ボリュームダッシュボードが10秒未満でロードされるようになり、インターフェイスの速度と効率が大幅に向上しました。このプレビュー版は一部のお客様にご利用いただけ、これらの改善点をいち早くご紹介しています。



==== サードパーティ製Wasabiオブジェクトストアのサポート（プレビュー）

BlueXP  のバックアップとリカバリでは、Wasabiを中心にサードパーティのオブジェクトストアのサポートが拡張されました。この新しいプレビュー機能を使用すると、バックアップとリカバリのニーズに合わせてS3互換オブジェクトストアを活用できます。



===== Wasabiの使用を開始する

サードパーティ製ストレージをオブジェクトストアとして使用するには、BlueXP  Connectorでフラグを有効にする必要があります。その後、サードパーティオブジェクトストアの接続の詳細を入力し、バックアップとリカバリのワークフローに統合できます。

.手順
. コネクタにSSH接続します。
. BlueXP  バックアップとリカバリのCBSサーバコンテナに移動します。
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. Vimまたはその他のエディタを使用して、フォルダ内のファイルを `config`開き `default.json`ます。
+
[listing]
----
vi default.json
----
. 「：false」を「true」に `allow-s3-compatible`変更し `allow-s3-compatible`ます。
. 変更を保存します。
. コンテナを終了します。
. BlueXP  バックアップおよびリカバリCBSサーバコンテナを再起動します。


.結果
コンテナが再びオンになったら、BlueXP  バックアップとリカバリのUIを開きます。バックアップを開始するか、バックアップ戦略を編集すると、新しいプロバイダ「S3 Compatible」が、AWS、Microsoft Azure、Google Cloud、StorageGRID、ONTAP S3の他のバックアッププロバイダとともにリストされます。



===== プレビューモードの制限事項

この機能のプレビュー中は、次の制限事項を考慮してください。

* Bring Your Own Bucket（BYOB）はサポートされていません。
* ポリシーでDataLockを有効にすることはできません。
* ポリシーでアーカイブモードを有効にすることはできません。
* オンプレミスのONTAP環境のみがサポートされます。
* MetroClusterはサポートされていません。
* バケットレベルの暗号化を有効にするオプションはサポートされていません。


このプレビューでは、すべての機能をリリースする前に、この新機能について確認し、サードパーティのオブジェクトストアとの統合に関するフィードバックをお寄せいただくことを推奨します。



== 分類



=== 2025年6月10日



==== バージョン1.44

このBlueXP  分類リリースの内容は次のとおりです。

.ガバナンスダッシュボードの更新時間の改善
ガバナンスダッシュボードの各コンポーネントの更新時間が改善されました。以下の表は、各コンポーネントの更新頻度を示しています。

[cols="1,1"]
|===
| コンポーネント | 更新時間 


| データの経過時間 | 24時間 


| カテゴリ | 24時間 


| データの概要 | 5分 


| 重複ファイル | 2時間 


| ファイルの種類 | 24時間 


| 非ビジネスデータ | 2時間 


| [ アクセス許可 ] を開きます | 24時間 


| 保存済みの検索 | 2時間 


| 機密データと幅広い権限 | 24時間 


| データのサイズ | 24時間 


| 古いデータ | 2時間 


| 機密レベル別トップデータリポジトリ | 2時間 
|===
重複ファイル、非ビジネスデータ、保存済み検索、古いデータ、機密レベル別上位データリポジトリの各コンポーネントは、最終更新時刻の確認と手動更新が可能です。ガバナンスダッシュボードの詳細については、以下をご覧ください。 xref:task-controlling-governance-data.html[組織に保存されているデータに関するガバナンスの詳細を表示する] 。

.パフォーマンスとセキュリティの改善
BlueXP 分類のパフォーマンス、メモリ消費、セキュリティを改善するための機能強化が行われました。

.バグ修正
Redis がアップグレードされ、BlueXP 分類の信頼性が向上しました。BlueXP分類では、スキャン中のファイル数レポートの精度を向上させるために Elasticsearch が使用されるようになりました。



=== 2025年5月12日



==== バージョン1.43

このBlueXP  分類リリースの内容は次のとおりです。

.分類スキャンの優先順位付け
BlueXP  分類では、マッピングのみのスキャンに加えて、マップスキャンとスキャンの分類を優先する機能がサポートされており、最初に完了するスキャンを選択できます。MapおよびClassifyスキャンの優先順位付けは、スキャンの開始中および開始前にサポートされます。進行中のスキャンに優先順位を付けることを選択した場合は、マッピングスキャンと分類スキャンの両方に優先順位が付けられます。

詳細については、を参照してください link:task-managing-repo-scanning.html#prioritize-scans["スキャンの優先順位付け"]。

.カナダの個人識別情報（PII）データカテゴリのサポート
BlueXP  分類スキャンは、カナダのPIIデータカテゴリを識別します。これらのカテゴリには、カナダのすべての州と地域の銀行情報、パスポート番号、社会保険番号、運転免許証番号、健康カード番号が含まれます。

詳細については、を参照してください xref:reference-private-data-categories.adoc#types-of-personal-data[個人データのカテゴリ]。

.カスタム分類（プレビュー）
BlueXP  分類では、MapおよびClassifyスキャンのカスタム分類がサポートされます。カスタム分類を使用すると、正規表現を使用して組織固有のデータをキャプチャするようにBlueXP  スキャンを調整できます。この機能は現在プレビュー中です。

詳細については、を参照してください xref:task-custom-classification.adoc[カスタム分類の追加]。

.[保存済み検索]タブ
**Policies**タブの名前が変更されましたxref:task-using-policies.html[**保存された検索**]。機能は同じです。

.スキャンイベントをBlueXP  タイムラインに送信
BlueXP  分類では、への分類イベント（スキャンの開始時と終了時）の送信がサポートされますlink:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["BlueXP  のタイムライン"^]。

.セキュリティの更新
* Kerasパッケージが更新され、脆弱性（BDSA-2025-0107およびBDSA-2025-1984）が緩和されました。
* Dockerコンテナの設定が更新されました。コンテナは、未加工のネットワークパケットを作成するためのホストのネットワークインターフェイスにアクセスできなくなります。不要なアクセスを減らすことで、潜在的なセキュリティリスクを軽減します。


.パフォーマンスの強化
RAMの使用量を削減し、BlueXP  分類の全体的なパフォーマンスを向上させるために、コードの拡張が実装されています。

.バグ修正
StorageGRIDスキャンが失敗する原因となったバグ、調査ページのフィルタオプションがロードされない問題、および大量評価のためにダウンロードされないデータ検出評価が修正されました。



=== 2025年4月14日



==== バージョン1.42

このBlueXP  分類リリースの内容は次のとおりです。

.作業環境の一括スキャン
BlueXP  の分類では、作業環境の一括操作がサポートされます。マッピングスキャンの有効化、スキャンのマッピングと分類の有効化、スキャンの無効化、または作業環境内のボリューム間でのカスタム構成の作成を選択できます。個 々 のボリュームを選択した場合は、一括選択よりも優先されます。一括操作を実行するには'**Configuration**ページに移動して選択します

.調査レポートをローカルにダウンロード
BlueXP  分類では、データ調査レポートをローカルにダウンロードしてブラウザで表示する機能がサポートされています。ローカルオプションを選択した場合、データ調査はCSV形式でのみ使用でき、最初の10,000行のデータのみが表示されます。

詳細については、を参照してください link:task-investigate-data.html#create-the-data-investigation-report["BlueXP  分類を使用して、組織に保存されているデータを調査する"]。



=== 2025年3月10日



==== バージョン1.41

このBlueXP  分類リリースには、全般的な改善とバグ修正が含まれています。次の内容も含まれます。

.スキャンステータス
BlueXP  分類は、ボリューム上の_initial_mappingスキャンと分類スキャンのリアルタイムの進行状況を追跡します。個別のプログレッシブバーはマッピングスキャンと分類スキャンを追跡し、スキャンされたファイルの割合を示します。進行状況バーにカーソルを合わせると、スキャンされたファイル数と合計ファイル数を表示することもできます。スキャンのステータスを追跡することで、スキャンの進捗状況をより詳細に把握できるため、スキャンの計画やリソースの割り当てをより適切に把握できます。

スキャンのステータスを表示するには、BlueXP  分類で** Configuration **に移動し、** Working Environment構成**を選択します。進行状況はボリュームごとに1行に表示されます。



=== 2025年2月19日



==== バージョン1.40

このBlueXP  分類リリースには、次の更新が含まれています。

.RHEL 9.5のサポート
このリリースでは、以前のサポートバージョンに加えて、Red Hat Enterprise Linux v9.5もサポートされます。これは、ダークサイトの導入を含む、BlueXP  分類の手動オンプレミスインストールに適用されます。

次のオペレーティングシステムでは、Podmanコンテナエンジンを使用する必要があり、BlueXP  分類バージョン1.30以降が必要です。Red Hat Enterprise Linuxバージョン8.8、8.10、9.0、9.1、9.2、9.3、9.4、9.5。

.マッピングのみのスキャンの優先順位付け
マッピングのみのスキャンを実行する場合は、最も重要なスキャンに優先順位を付けることができます。この機能は、多数の作業環境があり、優先度の高いスキャンを先に完了させたい場合に役立ちます。

デフォルトでは、スキャンは開始順序に基づいてキューに入れられます。スキャンに優先順位を付ける機能を使用すると、スキャンをキューの先頭に移動できます。複数のスキャンに優先順位を付けることができます。優先順位は、先入れ先出し順で指定されます。つまり、最初に優先順位を付けたスキャンがキューの先頭に移動し、2番目に優先順位を付けたスキャンがキューの2番目に移動します。

優先度は1回だけ付与されます。マッピングデータの自動再スキャンは、デフォルトの順序で実行されます。

優先順位付けはに限定されlink:concept-cloud-compliance.html["マッピングのみのスキャン"]、マップスキャンおよび分類スキャンでは使用できません。

詳細については、を参照してください link:task-managing-repo-scanning.html#prioritize-scans["スキャンの優先順位付け"]。

.すべてのスキャンを再試行
BlueXP  分類では、失敗したすべてのスキャンをバッチ再試行する機能がサポートされています。

**すべて再試行**機能を使用して、バッチ操作でスキャンを再試行できます。ネットワークの停止などの一時的な問題が原因で分類スキャンが失敗した場合は、個 々 に再試行するのではなく、ボタン1つですべてのスキャンを同時に再試行できます。スキャンは必要に応じて何度でも再試行できます。

すべてのスキャンを再試行するには：

. BlueXP  分類メニューから*設定*を選択します。
. 失敗したスキャンをすべて再試行するには、*[すべてのスキャンを再試行]*を選択します。


.カテゴリ化モデルの精度の向上
の機械学習モデルの精度はlink:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["事前定義されたカテゴリ"]11%向上しました。



=== 2025年1月22日



==== バージョン1.39

このBlueXP  分類リリースでは、データ調査レポートのエクスポートプロセスが更新されます。このエクスポートの更新は、データに対して追加の分析を実行したり、データに追加の視覚化を作成したり、データ調査の結果を他のユーザーと共有したりするのに役立ちます。

以前は、データ調査レポートのエクスポートは10,000行に制限されていました。このリリースでは、すべてのデータをエクスポートできるように制限が解除されました。この変更により、Data Investigationレポートからより多くのデータをエクスポートできるようになり、データ分析の柔軟性が向上します。

作業環境、ボリューム、デスティネーションフォルダ、JSON形式またはCSV形式を選択できます。エクスポートされたファイル名には、データがいつエクスポートされたかを識別するのに役立つタイムスタンプが含まれています。

サポートされる作業環境は次のとおりです。

* Cloud Volumes ONTAP
* FSX for ONTAP の略
* ONTAP
* 共有グループ


Data Investigationレポートからのデータのエクスポートには、次の制限事項があります。

* ダウンロードするレコードの最大数は5億個です（ファイル、ディレクトリ、およびテーブル）。
* 100万レコードの輸出には約35分かかると予想されている。


データ調査とレポートの詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["組織に保存されているデータの調査"]。



=== 2024年12月16日



==== バージョン1.38

このBlueXP  分類リリースには、全般的な改善とバグ修正が含まれています。



== Cloud Volumes ONTAP



=== 2025年5月29日



==== Cloud Volumes ONTAP 9.15.1でイネーブルになっているプライベートモード展開

Cloud Volumes ONTAP 9.15.1をプライベートモードでAWS、Azure、Google Cloudに導入できるようになりました。プライベートモードは、Cloud Volumes ONTAP 9.15.1のシングルノード環境とハイアベイラビリティ（HA）環境の両方で有効になります。

プライベートモード配置の詳細については、を参照してくださいhttps://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html#restricted-mode["BlueXPの導入モードについて説明します"^]。



=== 2025年5月12日



==== Azure Marketplaceを通じたBlueXP  の導入環境の調査

BlueXP  では、Azure Marketplaceから直接導入されたCloud Volumes ONTAPシステムを検出できるようになりました。つまり、これらのシステムを他のCloud Volumes ONTAPシステムと同様に、BlueXP  で作業環境として追加および管理できるようになりました。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploy-cvo-azure-mktplc.html["Azure MarketplaceからCloud Volumes ONTAPを導入"^]



==== Azureテナントのデータを階層化する機能

Cloud Volumes ONTAP作業環境をあるテナントで作成し、BlueXP  Connectorを別のテナントで作成するシナリオで、Azureテナントの階層化を有効にできるようになりました。この機能を使用すると、同じコネクタを使用して複数のAzureテナントのデータを階層化できます。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html#requirements-to-tier-data-for-an-azure-tenant["Azureテナントのデータを階層化するための要件"^]



=== 2025年4月16日



==== Azureでサポートされる新しいリージョン

Cloud Volumes ONTAP 9.12.1 GA以降は、次のリージョンのAzureの単一または複数のアベイラビリティゾーンに導入できるようになりました。これには、シングルノード環境とハイアベイラビリティ（HA）環境の両方がサポートされます。

* スペイン中部
* メキシコ中部


すべてのリージョンのリストについては、を参照して https://bluexp.netapp.com/cloud-volumes-global-regions["Azureのグローバルリージョンマップ"^]ください。



== Cloud Volumes Service for Google Cloud



=== 2020年9月9日



==== Cloud Volumes Service for Google Cloud のサポート

Cloud Volumes Service for Google CloudをBlueXPから直接管理できるようになりました。

* 作業環境をセットアップして作成
* Linux クライアントおよび UNIX クライアント用に、 NFSv3 ボリュームと NFSv4.1 ボリュームを作成および管理します
* Windows クライアント用に SMB 3.x ボリュームを作成して管理します
* ボリューム Snapshot を作成、削除、およびリストアします




== コピーと同期



=== 2025年2月2日



==== データブローカーの新しいOSサポート

Red Hat Enterprise 9.4、Ubuntu 23.04、およびUbuntu 24.04を実行するホストでデータブローカーがサポートされるようになりました。

https://docs.netapp.com/us-en/bluexp-copy-sync/task-installing-linux.html#linux-host-requirements["Linuxホストの要件の表示"]です。



=== 2024年10月27日



==== バグ修正

BlueXPのコピーおよび同期サービスとデータブローカーを更新し、いくつかのバグを修正しました。新しいデータブローカーのバージョンは1.0.56です。



=== 2024年9月16日



==== バグ修正

BlueXPのコピーおよび同期サービスとデータブローカーを更新し、いくつかのバグを修正しました。新しいデータブローカーのバージョンは1.0.55です。



== デジタルアドバイザ



=== 2025年5月8日



==== AutoSupportウィジェット

AutoSupportウィジェットが拡張され、AutoSupportデータの送信を停止したシステムの詳細を示すポップアップが表示されるようになりました。AutoSupportを有効にすることで、ダウンタイムのリスクを軽減し、プロアクティブなシステム健全性管理をサポート



==== サポート契約レポート

サポート契約レポートが強化され、新しいASP/LSGフラグフィールドが追加されました。このフィールドでは、認定サポートパートナー（ライフサイクルサービス認定）の対象となるシステムをフィルタして特定できます。



==== Sustainability Dashboard

サステナビリティプレゼンテーションに含まれているリンクを使用して、Sustainabilityダッシュボードを起動できるようになりました。



=== 2025年3月5日



==== Upgrade Advisor を使用します

* Disk Qualification Package（DQP）を使用して、事前に定義された健常性とパフォーマンスの条件に従って、ディスクコントローラとストレージデバイスファームウェアを自動的に更新できるようになりました。これにより、潜在的な障害が減少し、システム全体の信頼性が向上します。
* システムと最新のタイムゾーン定義の整合性を自動的に維持するために、タイムゾーンデータベース（DB）が導入されました。これにより、タイムゾーンルールが変更された場合でも、時間依存の操作がスムーズに継続されます。




=== 2024年12月12日



==== Upgrade Advisor を使用します

更新に推奨されるストレージファームウェア、SP / BMCファームウェア、およびAutonomous Ransomware Package（ARP）を確認できるようになりました。link:https://docs.netapp.com/us-en/active-iq/view-firmware-update-recommendations.html["ファームウェアアップデートの推奨事項を表示する方法"]です。



== デジタルウォレット



=== 2025年3月10日



==== サブスクリプションを削除する機能

サブスクリプションを解除した場合は、デジタルウォレットからサブスクリプションを削除できるようになりました。



==== Marketplaceサブスクリプションの消費容量を表示

PAYGOサブスクリプションを表示するときに、サブスクリプションの消費容量を表示できるようになりました。



=== 2025年2月10日

BlueXP  デジタルウォレットは使いやすさを考慮して再設計され、追加のサブスクリプションとライセンス管理が可能になりました。



==== 新しい概要ダッシュボード

デジタルウォレットのホームページには、NetAppライセンスとMarketplaceサブスクリプションの更新されたダッシュボードがあり、特定のサービス、ライセンスタイプ、必要なアクションをドリルダウンできます。



==== クレデンシャルへのサブスクリプションの設定

BlueXP  デジタルウォレットで、プロバイダーの資格情報へのサブスクリプションを構成できるようになりました。通常は、Marketplaceのサブスクリプションまたは年間契約を最初にサブスクライブするときに実行します。以前は、サブスクリプションのクレデンシャルを変更するには、[Credentials]ページを使用する必要がありました。



==== サブスクリプションと組織の関連付け

サブスクリプションが関連付けられている組織をデジタルウォレットから直接更新できるようになりました。



==== Cloud Volume ONTAPライセンスの管理

ホームページまたは*直接ライセンス*タブでCloud Volumes ONTAPライセンスを管理できるようになりました。[Marketplace subscriptions]タブを使用して、サブスクリプション情報を表示します。



=== 2024年3月5日



==== BlueXPディザスタリカバリ

BlueXPのデジタルウォレットで、BlueXPディザスタリカバリのライセンスを管理できるようになりました。ライセンスの追加、ライセンスの更新、およびライセンス容量に関する詳細の表示を行うことができます。

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["BlueXPデータサービスのライセンスを管理する方法"]



=== 2023年7月30日



==== 使用状況レポートの機能拡張

Cloud Volumes ONTAP使用状況レポートにいくつかの改善点が追加されました。

* TiB単位が列名に追加されました。
* シリアル番号の新しい_node_fieldが追加されました。
* [Storage VMs]使用状況レポートに新しい_Workload Type_columnが追加されました。
* 作業環境の名前がStorage VMとボリュームの使用状況レポートに表示されるようになりました。
* ボリュームタイプ_file_に_Primary（Read/Write）_というラベルが付けられます。
* ボリュームタイプ_secondary_のラベルが_secondary（DP）_に変更されました。


使用状況レポートの詳細については、を参照してください。 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["使用状況レポートをダウンロードします"]。



== ディザスタリカバリ



=== 2025年6月30日

バージョン4.2.4P2



==== 発見の改善

このアップデートにより検出プロセスが改善され、検出に必要な時間が短縮されます。



=== 2025年6月23日

バージョン4.2.4P1



==== サブネットマッピングの改善

このアップデートでは、「サブネットマッピングの追加と編集」ダイアログに新しい検索機能が追加されました。検索語を入力するだけで特定のサブネットを素早く見つけられるため、サブネットマッピングの管理が容易になります。



=== 2025年6月9日

バージョン4.2.4



==== Windows ローカル管理者パスワードソリューション (LAPS) のサポート

Windows ローカル管理者パスワード ソリューション (Windows LAPS) は、Active Directory 上のローカル管理者アカウントのパスワードを自動的に管理およびバックアップする Windows 機能です。

ドメインコントローラーの詳細を入力することで、サブネットマッピングオプションを選択し、LAPSオプションをチェックできるようになりました。このオプションを使用すると、仮想マシンごとにパスワードを入力する必要がなくなります。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== 2025年5月13日

バージョン4.2.3



==== サブネットマッピング

このリリースでは、サブネットマッピングを使用してフェイルオーバー時のIPアドレスを新しい方法で管理できます。これにより、各vCenterにサブネットを追加できます。その場合は、IPv4 CIDR、デフォルトゲートウェイ、および各仮想ネットワークのDNSを定義します。

フェイルオーバー時に、BlueXP  ディザスタリカバリは、マッピングされた仮想ネットワーク用に提供されたCIDRを参照して、各vNICの適切なIPアドレスを決定し、それを使用して新しいIPアドレスを取得します。

例：

* networkA = 10.1.1.0/24
* ネットワークB = 192.168.1.0/24


VM1には、NetworkAに接続されたvNIC（10.1.1.50）があります。NetworkAは、レプリケーションプラン設定でNetworkBにマッピングされます。

フェイルオーバー時、BlueXP  ディザスタリカバリは元のIPアドレス（10.1.1）のネットワーク部分を置き換え、元のIPアドレス（10.1.1.50）のホストアドレス（.50）を維持します。VM1の場合、BlueXP  ディザスタリカバリは、NetworkBのCIDR設定を確認し、ホスト部分（.50）を維持しながら、NetworkBネットワーク部分192.168.1を使用してVM1の新しいIPアドレスを作成します。新しいIPは192.168.1.50になります。

つまり、ホストアドレスは同じままですが、ネットワークアドレスはサイトサブネットマッピングで設定されているものに置き換えられます。これにより、フェイルオーバー時のIPアドレスの再割り当てをより簡単に管理できます。特に、数百のネットワークと数千のVMを管理する必要がある場合に便利です。

サイトにサブネットマッピングを含める方法の詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenterサーバサイトを追加"]。



==== 保護をスキップ

レプリケーションプランのフェイルオーバー後にサービスが逆保護関係を自動的に作成しないように、保護をスキップできるようになりました。これは、BlueXP  ディザスタリカバリでリストアしたサイトをオンラインに戻す前に、そのサイトで追加の処理を実行する場合に便利です。

フェイルオーバーを開始すると、デフォルトでは、元のソースサイトがオンラインの場合、レプリケーションプランの各ボリュームに対して逆保護関係が自動的に作成されます。これは、サービスがターゲットサイトからソースサイトへのSnapMirror関係を作成することを意味します。フェイルバックを開始すると、SnapMirror関係も自動的に反転されます。

フェイルオーバーを開始するときに、*[Skip protection]*オプションを選択できるようになりました。これにより、サービスはSnapMirror関係を自動的に反転しません。代わりに、書き込み可能なボリュームはレプリケーション計画の両側に残ります。

元のソースサイトがオンラインに戻ったら、レプリケーションプランの[アクション]メニューから*[リソースの保護]*を選択して、逆保護を設定できます。これにより、プラン内の各ボリュームに対して逆レプリケーション関係の作成が試行されます。保護が回復するまで、このジョブを繰り返し実行できます。保護が復元されたら、通常の方法でフェイルバックを開始できます。

保護のスキップの詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["リモートサイトへのアプリケーションのフェイルオーバー"]。



==== SnapMirrorスケジュールによるレプリケーション計画の更新

BlueXP  ディザスタリカバリでは、標準のONTAP SnapMirrorポリシースケジューラやONTAPとのサードパーティ統合など、外部のSnapshot管理ソリューションの使用がサポートされるようになりました。レプリケーションプラン内のすべてのデータストア（ボリューム）にすでに別の場所で管理されているSnapMirror関係がある場合は、それらのSnapshotをBlueXP  ディザスタリカバリのリカバリポイントとして使用できます。

設定するには、[Replication plan]>[Resource mapping]セクションで、データストアマッピングの設定時に*[Use platform managed backups and retention schedules]*チェックボックスをオンにします。

このオプションを選択した場合、BlueXP  ディザスタリカバリではバックアップスケジュールが設定されません。ただし、テスト、フェイルオーバー、フェイルバック操作のためにスナップショットが作成される可能性があるため、保持スケジュールを設定する必要があります。

この設定後、サービスは定期的にスケジュールされたスナップショットを作成せず、代わりに外部エンティティに依存してこれらのスナップショットを作成および更新します。

レプリケーションプランでの外部スナップショットソリューションの使用の詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== 2025年4月16日

バージョン4.2.2



==== VMのスケジュールされた検出

BlueXP  ディザスタリカバリでは、24時間に1回検出が実行されます。このリリースでは、ニーズに合わせて調査スケジュールをカスタマイズし、必要なときにパフォーマンスへの影響を軽減できるようになりました。たとえば、VMの数が多い場合は、検出スケジュールを48時間ごとに実行するように設定できます。VMの数が少ない場合は、検出スケジュールを12時間ごとに実行するように設定できます。

検出をスケジュールしない場合は、スケジュールされた検出オプションを無効にして、いつでも手動で検出を更新できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenterサーバサイトを追加"]。



==== リソースグループデータストアのサポート

これまでは、VMごとにのみリソースグループを作成できました。このリリースでは、データストア別にリソースグループを作成できます。レプリケーション計画を作成し、その計画のリソースグループを作成すると、データストア内のすべてのVMが一覧表示されます。これは、多数のVMがあり、それらをデータストアでグループ化する場合に便利です。

データストアを含むリソースグループは、次の方法で作成できます。

* データストアを使用してリソースグループを追加する場合は、データストアのリストが表示されます。1つ以上のデータストアを選択してリソースグループを作成できます。
* レプリケーション計画を作成し、その計画内にリソースグループを作成すると、データストア内のVMが表示されます。


詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



==== 無償トライアルまたはライセンスの有効期限に関する通知

このリリースでは、ライセンスを取得する時間を確保するために、無料トライアルが60日後に期限切れになることを通知します。また、このリリースでは、ライセンスの有効期限が切れる日に通知が送信されます。



==== サービス更新の通知

このリリースでは、サービスがアップグレードされ、サービスがメンテナンスモードになったことを示すバナーが上部に表示されます。バナーはサービスのアップグレード中に表示され、アップグレードが完了すると消えます。アップグレードの進行中もUIで作業を続行できますが、新しいジョブを送信することはできません。スケジュールされたジョブは、更新が完了してサービスが本番モードに戻ると実行されます。



=== 2025年3月10日

バージョン4.2.1



==== インテリジェントなプロキシサポート

BlueXP  Connectorはインテリジェントプロキシをサポートしています。インテリジェントプロキシは、オンプレミス環境をBlueXP  サービスに接続するための、軽量で安全で効率的な方法です。VPNや直接インターネットアクセスを必要とせずに、環境とBlueXP  サービスの間に安全な接続を提供します。この最適化されたプロキシ実装により、ローカルネットワーク内のAPIトラフィックがオフロードされます。

プロキシが設定されている場合、BlueXP  ディザスタリカバリはVMwareまたはONTAPとの直接通信を試み、直接通信に失敗した場合は設定されたプロキシを使用します。

BlueXP  ディザスタリカバリプロキシを実装するには、HTTPSプロトコルを使用してコネクタとvCenter ServerおよびONTAPアレイをポート443で通信する必要があります。コネクタ内のBlueXP  ディザスタリカバリエージェントは、アクションの実行時にVMware vSphere、VC、またはONTAPと直接通信します。

BlueXP  ディザスタリカバリ用のインテリジェントプロキシの詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html["BlueXPディザスタリカバリのためのインフラのセットアップ"]。

BlueXP  で設定される一般的なプロキシの詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["プロキシサーバを使用するようにコネクタを設定します"^]。



==== 無償トライアルをいつでも終了

無料トライアルはいつでも停止することも、期限が切れるまで待つこともできます。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["無償トライアルを終了する"]



=== 2025年2月19日

バージョン4.2



==== VMFSストレージ上のVMとデータストアに対するASA R2のサポート

このリリースのBlueXP  ディザスタリカバリでは、VMFSストレージ上のVMとデータストアでASA R2がサポートされます。ASA R2システムでは、ONTAPソフトウェアは重要なSAN機能をサポートし、SAN環境でサポートされていない機能を削除します。

このリリースでは、ASA R2で次の機能がサポートされます。

* プライマリストレージのコンシステンシグループプロビジョニング（フラットコンシステンシグループのみ、階層構造を持たない1レベルのみ）
* バックアップ（整合グループ）処理（SnapMirrorの自動化など）


BlueXP  ディザスタリカバリでのASA R2のサポートには、ONTAP 9.16.1が使用されます。

データストアはONTAPボリュームまたはASA R2ストレージユニットにマウントできますが、BlueXP  ディザスタリカバリのリソースグループにONTAPのデータストアとASA R2のデータストアの両方を含めることはできません。リソースグループには、ONTAPのデータストアまたはASA R2のデータストアを選択できます。



=== 2024年10月30日



==== レポート作成

環境の分析に役立つレポートを生成してダウンロードできるようになりました。事前設計されたレポートには、フェイルオーバーとフェイルバックの概要、すべてのサイトのレプリケーションの詳細、過去7日間のジョブの詳細が表示されます。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["ディザスタリカバリレポートの作成"]。



==== 30日間の無償トライアル

BlueXP  ディザスタリカバリの30日間無償トライアルに申し込むことができます。以前は、無料トライアルは90日間でした。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["ライセンスをセットアップする"]。



==== レプリケーション計画の無効化と有効化

以前のリリースでは、日次スケジュールと週次スケジュールをサポートするために必要なフェイルオーバーテストスケジュールの構造が更新されていました。この更新では、新しい日次および週次フェイルオーバーテストスケジュールを使用できるように、既存のレプリケーションプランをすべて無効にして再度有効にする必要がありました。これは1回限りの要件です。

その方法は次のとおりです。

. トップメニューから*レプリケーションプラン*を選択します。
. 計画を選択し、[Actions]アイコンを選択してドロップダウンメニューを表示します。
. [*Disable*] を選択します。
. 数分後、*[有効化]*を選択します。




==== フォルダマッピング

レプリケーション計画を作成してコンピューティングリソースをマッピングするときに、フォルダをマッピングして、データセンター、クラスタ、およびホスト用に指定したフォルダにVMをリカバリできるようになりました。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



==== フェイルオーバー、フェイルバック、テストフェイルオーバーに使用できるVMの詳細

障害が発生し、フェイルオーバーの開始、フェイルバックの実行、またはフェイルオーバーのテストを行うときに、VMの詳細を確認し、再起動しなかったVMを特定できるようになりました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["リモートサイトへのアプリケーションのフェイルオーバー"]。



==== 順序付けされた起動順序でのVM起動遅延

レプリケーションプランを作成するときに、プラン内の各VMにブート遅延を設定できるようになりました。これにより、優先順位の高いすべてのVMが実行されてから、以降の優先順位の高いVMが起動されるように、VMの起動順序を設定できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



==== VMオペレーティングシステム情報

レプリケーションプランを作成すると、プラン内の各VMのオペレーティングシステムが表示されるようになります。これは、VMを1つのリソースグループにグループ化する方法を決定する際に役立ちます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



==== VM名のエイリアス設定

レプリケーション計画を作成するときに、ディザスタリカバリSITでVM名にプレフィックスとサフィックスを追加できるようになりました。これにより、プラン内のVMにわかりやすい名前を付けることができます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



==== 古いSnapshotをクリーンアップ

指定した保持数を超えて不要になったSnapshotは削除できます。Snapshotの保持数を減らすと、時間の経過とともにSnapshotが蓄積される可能性があります。削除してスペースを解放できるようになりました。これは、オンデマンドで、またはレプリケーションプランを削除するときにいつでも実行できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["サイト、リソースグループ、レプリケーションプラン、データストア、仮想マシンの情報を管理します。"]。



==== スナップショットの調整

ソースとターゲットの間で同期されていないスナップショットを調整できるようになりました。これは、BlueXP  ディザスタリカバリ以外のターゲットでSnapshotが削除された場合に発生することがあります。サービスは、ソース上のスナップショットを24時間ごとに自動的に削除します。ただし、これはオンデマンドで実行できます。この機能を使用すると、すべてのサイトでSnapshotの整合性を確保できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["レプリケーション計画の管理"]。



== Eシリーズシステム



=== 2025年5月12日



==== BlueXPアクセスロールが必要

BlueXP で E シリーズを表示、検出、または管理するには、組織管理者、フォルダーまたはプロジェクト管理者、ストレージ管理者、またはシステム ヘルス スペシャリストのいずれかのアクセス ロールが必要です。  https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["BlueXP アクセス ロールについて学習します。"^]



=== 2022年9月18日



==== Eシリーズのサポート

BlueXPからEシリーズシステムを直接検出できるようになりました。Eシリーズシステムを検出すると、ハイブリッドマルチクラウド全体のデータを包括的に把握できます。



== 経済効率



=== 2024年5月15日



==== 無効な機能

BlueXP  の経済効率化機能の一部が一時的に無効になりました。

* テクノロジの更新
* 容量の追加




=== 2024年3月14日



==== テクノロジ更新オプション

既存の資産を運用していて、テクノロジの更新が必要かどうかを判断する場合は、BlueXPの経済性に関するテクノロジ更新オプションを利用できます。現在のワークロードの簡単な評価を確認して推奨事項を確認できます。また、過去90日以内にAutoSupportログをNetAppに送信した場合は、新しいハードウェアでのワークロードのパフォーマンスを確認するためのワークロードシミュレーションを提供できるようになりました。

ワークロードを追加して、既存のワークロードをシミュレーションから除外することもできます。

これまでは、アセットの評価を受けて、テクノロジの更新が推奨されるかどうかを判断することしかできませんでした。

この機能は、左側のナビゲーションの機器更改（Tech Refresh）オプションに含まれるようになりました。

の詳細については、を https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["テクノロジの更新を評価する"]参照してください。



=== 2023年11月8日



==== テクノロジの更新

今回リリースされたBlueXPの経済効率化機能には、資産を評価し、テクノロジの更新が推奨されるかどうかを確認する新しいオプションが含まれています。このサービスには、左側のナビゲーションにある新しい機器更改（Tech Refresh）オプションのほか、現在のワークロードと資産を評価するための新しいページ、推奨事項を記載したレポートが含まれています。



== エッジキャッシュ

BlueXP  エッジキャッシングサービスは、2024年8月7日に削除されました。



== Google クラウドストレージ



=== 2023年7月10日



==== BlueXPから新しいバケットを追加したり、既存のバケットを管理したりできます

BlueXPキャンバスでGoogle Cloud Storageのバケットを表示できるようになりました。BlueXP  から直接、新しいバケットを追加したり、既存のバケットのプロパティを変更したりできるようになりました。 https://docs.netapp.com/us-en/bluexp-google-cloud-storage/task-add-gcp-bucket.html["新しいGoogle Cloud Storageバケットを追加する方法をご覧ください"]です。



== Keystone



=== 2025年6月19日



==== BlueXPのKeystoneダッシュボード

BlueXPからKeystoneダッシュボードに直接アクセスできるようになりました。この統合により、すべてのKeystoneサブスクリプションとその他のNetAppサービスを一元的に監視、管理、追跡できるようになります。

BlueXP の Keystone ダッシュボードを使用すると、次のことが可能になります。

* すべてのサブスクリプションの詳細、容量の使用状況、資産を 1 か所で表示します。
* サブスクリプションを簡単に管理し、ニーズの変化に応じて変更をリクエストできます。
* ストレージ環境の最新情報を常に把握してください。


開始するには、BlueXP の左側のナビゲーション メニューで *ストレージ > Keystone* に移動します。詳細については、を参照して link:https://docs.netapp.com/us-en/keystone-staas/integrations/dashboard-overview.html["Keystoneダッシュボードの概要"]ください。



== Kubernetes

Kubernetesクラスタの検出と管理のサポートが2024年8月7日に廃止されました。



== 移行レポート

BlueXP  移行レポートサービスは、2024年8月7日に削除されました。



== オンプレミスの ONTAP クラスタ



=== 2025年5月12日



==== BlueXPアクセスロールが必要

オンプレミスの ONTAP クラスターを表示、検出、または管理するには、組織管理者、フォルダーまたはプロジェクト管理者、ストレージ管理者、またはシステム ヘルス スペシャリストのいずれかのアクセス ロールが必要になります。 link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["BlueXP アクセス ロールについて学習します。"^]



=== 2024年11月26日



==== プライベートモードを使用するASA R2システムのサポート

BlueXP  をプライベートモードで使用しているときに、NetApp ASA R2システムを検出できるようになりました。このサポートは、BlueXP  の3.9.46プライベートモードリリース以降で利用できます。

* https://docs.netapp.com/us-en/asa-r2/index.html["ASA R2システムの詳細"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXPの導入モードについて説明します"^]




=== 2024年10月7日



==== ASA R2システムのサポート

標準モードまたは制限モードでBlueXP  を使用している場合、BlueXP  でNetApp ASA R2システムを検出できるようになりました。NetApp ASA R2システムを検出して作業環境を開くと、System Managerに直接移動します。

ASA R2システムでは、他の管理オプションは使用できません。[標準]ビューを使用したり、BlueXPサービスを有効にしたりすることはできません。

BlueXP  をプライベートモードで使用している場合、ASA R2システムの検出はサポートされません。

* https://docs.netapp.com/us-en/asa-r2/index.html["ASA R2システムの詳細"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXPの導入モードについて説明します"^]




== 運用の耐障害性



=== 2023年4月2日



==== BlueXP  運用耐障害性サービス

新しいBlueXPの運用耐障害性サービスとIT運用リスクの自動修復サービスを使用すると、システム停止や障害が発生する前に推奨される修正策を実装できます。

運用の耐障害性は、アラートとイベントを分析してサービスとソリューションの健全性、アップタイム、パフォーマンスを維持するのに役立つサービスです。

link:https://docs.netapp.com/us-en/bluexp-operational-resiliency/get-started/intro.html["BlueXPの運用耐障害性の詳細については、こちらをご覧ください"]。



== ランサムウェアからの保護



=== 2025年6月9日



==== ランディングページの更新

このリリースには、BlueXP ランサムウェア保護のランディング ページの更新が含まれており、無料トライアルの開始と検出が容易になります。



==== 準備訓練の最新情報

以前は、新しいサンプルワークロードへの攻撃をシミュレートすることで、ランサムウェア対策訓練を実行できました。この機能を使用すると、シミュレートされた攻撃を調査し、ワークロードを復旧できます。この機能を使用して、アラート通知、対応、復旧をテストします。これらの訓練は、必要に応じて何度でも実行およびスケジュールできます。

このリリースでは、BlueXP ランサムウェア保護ダッシュボードの新しいボタンを使用して、テスト ワークロードでランサムウェア準備ドリルを実行できるようになりました。これにより、制御された環境内でランサムウェア攻撃のシミュレーション、その影響の調査、ワークロードの効率的な回復が容易になります。

NFS ワークロードに加えて、CIFS (SMB) ワークロードでも準備ドリルを実行できるようになりました。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["ランサムウェア攻撃への備えの訓練を実施"]。



==== BlueXP分類の更新を有効にする

BlueXP  ランサムウェア対策サービスでBlueXP  分類を使用する前に、BlueXP  分類を有効にしてデータをスキャンする必要があります。データを分類すると、セキュリティ リスクを増大させる可能性のある個人を特定できる情報 (PII) を見つけるのに役立ちます。

BlueXPランサムウェア保護機能から、ファイル共有ワークロードにBlueXP分類を展開できます。「プライバシーの露出」列で「露出を特定」オプションを選択してください。分類サービスを有効にしている場合は、このアクションによって露出が特定されます。有効でない場合は、このリリースではダイアログボックスにBlueXP分類を展開するオプションが表示されます。「展開」を選択すると、BlueXP分類サービスのランディングページに移動し、サービスを展開できます。W

詳細については、  https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html["BlueXPの分類機能をクラウドに導入します"^] BlueXPランサムウェア保護内でサービスを利用するには、  https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect-classify.html["BlueXP  分類を使用して、個人を特定できる情報をスキャンします。"] 。



=== 2025年5月13日



==== BlueXP  ランサムウェア対策でサポートされていない作業環境に関するレポート

検出ワークフローで、BlueXP  ランサムウェア対策でサポート対象またはサポート対象外のワークロードにカーソルを合わせると、詳細が報告されます。これは、一部のワークロードがBlueXP  ランサムウェア対策サービスで検出されない理由を理解するのに役立ちます。

サービスで作業環境がサポートされない理由は数多くあります。たとえば、作業環境のONTAPバージョンが必要なバージョンよりも低い場合などです。サポートされていない作業環境にカーソルを合わせると、ツールチップに理由が表示されます。

初期検出時にサポートされていない作業環境を表示し、その結果をダウンロードすることもできます。検出結果は、[設定]ページの*[ワークロード検出]*オプションでも確認できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["BlueXPのランサムウェア対策でワークロードを検出"]。



=== 2025年4月29日



==== Amazon FSx for NetApp ONTAP をサポートします

このリリースでは、Amazon FSx for NetApp ONTAPがサポートされます。この機能は、BlueXP  ランサムウェア対策でFSx for ONTAPワークロードを保護するのに役立ちます。

FSx for ONTAPは、NetApp ONTAPストレージのパワーをクラウドで提供するフルマネージドサービスです。オンプレミスと同じ機能、パフォーマンス、管理機能を、AWSネイティブサービスの即応性と拡張性で提供します。

BlueXP  ランサムウェア対策のワークフローに次の変更が加えられました。

* 検出には、FSx for ONTAP 9.15作業環境のワークロードが含まれます。
* [Protection]タブには、FSx for ONTAP環境のワークロードが表示されます。この環境では、FSx for ONTAPバックアップサービスを使用してバックアップ処理を実行する必要があります。これらのワークロードは、BlueXP  ランサムウェア対策のSnapshotを使用してリストアできます。
+

TIP: FSx for ONTAPで実行されるワークロードのバックアップポリシーは、BlueXP  では設定できません。Amazon FSx for NetApp ONTAPで設定されている既存のバックアップポリシーは変更されません。

* アラートインシデントには、新しいFSx for ONTAP作業環境が表示されます。


詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html["BlueXP  ランサムウェア対策と作業環境の詳細"]。

サポートされるオプションについては、を参照して https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-limitations.html["BlueXP  ランサムウェア対策の制限事項"]ください。



==== BlueXPアクセスロールが必要

BlueXP ランサムウェア保護を表示、検出、または管理するには、組織管理者、フォルダーまたはプロジェクト管理者、ランサムウェア保護管理者、またはランサムウェア保護閲覧者のいずれかのアクセス ロールが必要です。

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するBlueXPのアクセスロールについて学ぶ"^]です。



=== 2025年4月14日



==== 準備状況ドリルレポート

このリリースでは、ランサムウェア攻撃の準備状況を示すドリルレポートを確認できます。準備のためのドリルでは、新しく作成したサンプルワークロードに対するランサムウェア攻撃をシミュレートできます。次に、シミュレートされた攻撃を調査し、サンプルワークロードをリカバリします。アラート通知、対応、リカバリの各プロセスをテストすることで、ランサムウェア攻撃が実際に発生した場合に備えておくことができます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["ランサムウェア攻撃への備えの訓練を実施"]。



==== 新しいロールベースアクセス制御のロールと権限

これまでは、ユーザの責任に基づいてロールと権限をユーザに割り当てることができました。これは、BlueXP  ランサムウェア対策へのユーザアクセスの管理に役立ちます。このリリースでは、BlueXP  ランサムウェア対策に固有の2つの新しいロールが追加され、権限が更新されました。新しいロールは次のとおりです。

* ランサムウェア対策管理者
* ランサムウェア対策ツール


権限の詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html["BlueXP  ランサムウェア対策機能へのロールベースアクセス"]。



==== 支払いの改善

このリリースには、支払いプロセスのいくつかの改善が含まれています。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html["ライセンスと支払いのオプションを設定する"]。



=== 2025年3月10日



==== 攻撃のシミュレーションと対応

このリリースでは、ランサムウェア攻撃をシミュレートして、ランサムウェアアラートへの対応をテストします。アラート通知、対応、リカバリの各プロセスをテストすることで、ランサムウェア攻撃が実際に発生した場合に備えておくことができます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["ランサムウェア攻撃への備えの訓練を実施"]。



==== 検出プロセスの機能拡張

このリリースでは、選択的な検出プロセスと再検出プロセスが強化されています。

* このリリースでは、以前に選択した作業環境に追加された新たに作成されたワークロードを検出できます。
* このリリースでは、_new_working environmentsを選択することもできます。この機能は、環境に追加される新しいワークロードを保護するのに役立ちます。
* これらの検出プロセスは、最初の検出プロセス中に実行することも、設定オプション内で実行することもできます。


詳細については、およびを https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["設定オプションを使用した機能の設定"]参照して https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["以前に選択した作業環境用に新しく作成されたワークロードを検出する"]ください。



==== 高い暗号化が検出されたときに生成されるアラート

このリリースでは、高いファイル拡張子が変更されていなくても、ワークロードで高い暗号化が検出されたときにアラートを表示できます。ONTAP Autonomous Ransomware Protection（ARP）AIを使用するこの機能は、ランサムウェア攻撃のリスクがあるワークロードを特定するのに役立ちます。この機能を使用して、影響を受けるファイルのリスト全体をダウンロードし、拡張子を変更するかどうかを指定します。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["検出されたランサムウェアに関するアラートに対応"]。



=== 2024年12月16日



==== Data Infrastructure Insights Storage Workload Securityを使用してユーザの異常な行動を検出

このリリースでは、Data Infrastructure Insights Storage Workload Securityを使用して、ストレージワークロードの異常なユーザ行動を検出できます。この機能を使用すると、潜在的なセキュリティ脅威を特定し、悪意のあるユーザをブロックしてデータを保護できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["検出されたランサムウェアに関するアラートに対応"]。

Data Infrastructure Insights Storage Workload Securityを使用して異常なユーザ行動を検出するには、事前にBlueXP  ransomware protection * Settings *オプションを使用してオプションを設定する必要があります。

を参照してください https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["BlueXPのランサムウェア対策の設定"]。



==== 検出して保護するワークロードを選択

このリリースでは、次の操作を実行できます。

* 各コネクタで、ワークロードを検出する作業環境を選択します。この機能は、環境内の特定のワークロードを保護し、他のワークロードを保護する必要がない場合に役立ちます。
* ワークロードの検出時に、コネクタごとにワークロードの自動検出を有効にすることができます。保護するワークロードを選択できます。
* 以前に選択した作業環境用に新しく作成されたワークロードを検出します。


を参照してください https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["ワークロードを検出"]。



== シユウフク

2024年4月22日にBlueXP修正サービスが削除されました。



== レプリケーション



=== 2022年9月18日



==== FSX for ONTAP to Cloud Volumes ONTAP の略

Amazon FSX for ONTAP ファイルシステムからCloud Volumes ONTAP にデータをレプリケートできるようになりました。

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["データレプリケーションの設定方法について説明します"]。



=== 2022年7月31日



==== ONTAP のFSXをデータソースとして使用します

Amazon FSX for ONTAP ファイルシステムから次のデスティネーションにデータをレプリケートできるようになりました。

* ONTAP 対応の Amazon FSX
* オンプレミスの ONTAP クラスタ


https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["データレプリケーションの設定方法について説明します"]。



=== 2021年9月2日



==== Amazon FSX for ONTAP のサポート

Cloud Volumes ONTAP システムまたはオンプレミスの ONTAP クラスタから ONTAP ファイルシステム用の Amazon FSX にデータをレプリケートできるようになりました。

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["データレプリケーションの設定方法について説明します"]。



== ソフトウェアの更新



=== 2025年5月12日



==== BlueXPアクセスロールが必要

ソフトウェアアップデートをインストールするには、以下のいずれかのアクセスロールが必要です：*組織管理者*、*フォルダまたはプロジェクト管理者*、*ストレージ管理者*、*ストレージ閲覧者*、または*ストレージヘルススペシャリスト*。ストレージ閲覧者ロールを持つユーザーには、ソフトウェアアップデートに関連する様々な権限が付与されますが、ソフトウェアアップデートをインストールすることはできません。 link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["BlueXP アクセス ロールについて学習します。"^]



=== 2025年4月2日



==== 軽減されたリスク

BlueXP  ソフトウェア更新プログラムの概要セクションに、オペレーティングシステムの更新によって軽減できるリスクの総数が表示されるようになりました。これにより、インストールベースのセキュリティと安定性の向上を評価できます。



=== 2024年8月7日



==== ONTAPの更新

BlueXP  ソフトウェアアップデートサービスは、リスクを軽減し、お客様がONTAPの機能を十分に活用できるようにすることで、シームレスなアップデートエクスペリエンスをユーザに提供します。

詳細については、をご覧ください link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["BlueXP  ソフトウェアアップデート"]。



== StorageGRID



=== 2024年8月7日



==== 新しい詳細ビュー

StorageGRID 11.8以降では、使い慣れたグリッドマネージャのインターフェイスを使用して、BlueXP  からStorageGRIDシステムを管理できます。

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["アドバンストビューを使用したStorageGRIDの管理方法"]です。



==== StorageGRID管理インターフェイス証明書の確認と承認

BlueXP  からStorageGRIDシステムを検出するときに、StorageGRID管理インターフェイスの証明書を確認して承認できるようになりました。検出されたグリッドで、最新のStorageGRID管理インターフェイス証明書を確認して承認することもできます。

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["システム検出時にサーバ証明書を確認および承認する方法について説明します。"]



=== 2022年9月18日



==== StorageGRID のサポート

StorageGRID システムをBlueXPから直接検出できるようになりました。StorageGRID を検出すると、ハイブリッドマルチクラウド全体のデータを包括的に把握できます。



== 階層化



=== 2023年8月9日



==== バケット名にカスタムプレフィックスを使用する

以前は、バケット名を定義する際にデフォルトの「fabric-pool」プレフィックス（_fabric-pool-bucket1_など）を使用する必要がありました。バケットに名前を付けるときにカスタムプレフィックスを使用できるようになりました。この機能は、データをAmazon S3に階層化する場合にのみ使用できます。 https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["詳細はこちら。"]。



==== すべてのBlueXPコネクタでクラスタを検索

環境内のすべてのストレージシステムの管理に複数のコネクタを使用している場合は、階層化を実装する一部のクラスタが別 々 のコネクタに配置されている可能性があります。特定のクラスタを管理しているコネクタが不明な場合は、BlueXP階層化を使用してすべてのコネクタを検索できます。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["詳細はこちら。"]。



=== 2023年7月4日



==== アクセス頻度の低いデータを転送するための帯域幅の調整

BlueXP階層化をアクティブ化すると、ONTAPは無制限のネットワーク帯域幅を使用して、アクセス頻度の低いデータをクラスタ内のボリュームからオブジェクトストレージに転送できます。階層化トラフィックが通常のユーザワークロードに影響していることに気付いた場合は、転送中に使用できる帯域幅を調整できます。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["詳細はこちら。"]です。



==== 通知センターに表示される階層化イベント

クラスタがコールドデータの20%未満（データを階層化しないクラスタを含む）を階層化しているときに、階層化イベント「Tier additional data from cluster <name> to object storage efficiency」が通知として表示されるようになりました。

本通知は、システムの効率化とストレージコストの削減を目的とした「推奨事項」です。これにより、へのリンクが提供されます https://bluexp.netapp.com/cloud-tiering-service-tco["BlueXP階層化サービス（TCO）とコスト削減試算ツールです"^] コスト削減額の計算に役立ちます。



=== 2023年4月3日



==== [ライセンス]タブが削除されました

BlueXP階層化インターフェイスから[ライセンス]タブが削除されました。従量課金制（PAYGO）サブスクリプションのすべてのライセンスに、BlueXP階層化オンプレミスダッシュボードからアクセスできるようになりました。また、このページからBlueXPのデジタルウォレットへのリンクもあり、BlueXP階層化サービスのお客様所有のライセンスの使用（BYOL）を表示および管理できます。



==== 階層化タブの名前変更と更新

[Clusters Dashboard]タブの名前が[Clusters]に変更され、[On-Prem Overview]タブの名前が[On-Premises Dashboard]に変更されました。これらのページには、階層化構成を追加してストレージスペースを最適化できるかどうかを評価するための情報が追加されています。



== ボリュームキャッシュ



=== 2023年6月4日



==== ボリュームキャッシュ

ONTAP 9ソフトウェアの機能であるボリュームキャッシングは、ファイル配信を簡易化し、ユーザやコンピューティングリソースの近くにリソースを配置することでWANレイテンシを低減し、WAN帯域幅のコストを削減するリモートキャッシング機能です。ボリュームキャッシングは、リモートの場所にある書き込み可能な永続的ボリュームを提供します。BlueXPのボリュームキャッシュを使用すると、データへのアクセスを高速化したり、アクセス頻度の高いボリュームのトラフィックをオフロードしたりできます。キャッシュボリュームは、特にクライアントが同じデータに繰り返しアクセスする必要がある場合に、読み取り処理が大量に発生するワークロードに最適です。

BlueXPボリュームキャッシングを使用すると、特にAmazon FSx for NetApp ONTAP、Cloud Volumes ONTAP、オンプレミスの作業環境向けに、クラウド向けのキャッシュ機能を利用できます。

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["BlueXPのボリュームキャッシュの詳細については、こちらをご覧ください"]。



== ワークロードファクトリ



=== 2025年6月29日



==== データベースの権限の更新

データベースの _読み取り専用_ モードで次の権限が利用できるようになりました。  `cloudwatch:GetMetricData` 。

https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["アクセス権参照変更ログ"]



==== BlueXPワークロードファクトリー通知サービスのサポート

BlueXP ワークロードファクトリー通知サービスを使用すると、ワークロードファクトリーは BlueXP アラートサービスまたは Amazon SNS トピックに通知を送信できます。BlueXPアラートに送信された通知は、BlueXP アラートパネルに表示されます。ワークロードファクトリーが Amazon SNS トピックに通知を発行すると、トピックのサブスクライバー（ユーザーや他のアプリケーションなど）は、トピックに設定されたエンドポイント（E メールや SMS メッセージなど）で通知を受け取ります。

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["BlueXPワークロードファクトリー通知を構成する"]



=== 2025年5月4日



==== CloudShellオートコンプリートのサポート

BlueXP  ワークロードファクトリCloudShellを使用している場合は、コマンドの入力を開始してTabキーを押すと、使用可能なオプションが表示されます。複数の候補が存在する場合は、CLIに候補のリストが表示されます。この機能は、エラーを最小限に抑え、コマンド実行を高速化することで、生産性を向上させます。



==== 権限に関する用語を更新

ワークロード ファクトリのユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。



=== 2025年3月30日



==== ONTAP CLIコマンドについて、AIによって生成されたエラー応答がCloudShellで報告される

CloudShellを使用している場合、ONTAP CLIコマンドを発行してエラーが発生するたびに、失敗の説明、失敗の原因、詳細な解決策を含むAI生成のエラー応答を取得できます。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShellを使用"]



==== IAM：SimulatePermissionPolicy権限の更新

AWSアカウントのクレデンシャルを追加したり、生成AIワークロードなどの新しいワークロード機能を追加したりするときに、ワークロードファクトリコンソールから権限を管理できるようになりまし `iam:SimulatePrincipalPolicy`た。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["アクセス権参照変更ログ"]



=== 2025年2月2日



==== BlueXP  Workload FactoryコンソールでCloudShellを使用可能

CloudShellは、BlueXP  ワークロードファクトリコンソールのどこからでも使用できます。CloudShellを使用すると、BlueXP  アカウントで提供したAWSとONTAPのクレデンシャルを使用して、シェルに似た環境でAWS CLIコマンドまたはONTAP CLIコマンドを実行できます。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShellを使用"]



==== データベースの権限の更新

データベースの_read_modeで次の権限を使用できるようになりました `iam:SimulatePrincipalPolicy`。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["アクセス権参照変更ログ"]
